#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Illuminate\Contracts\Console\Kernel;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__ . '/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);

/*
// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
*/