services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: laravel-app
        container_name: laravel-app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - laravel
    redis:
        image: redis:alpine
        container_name: laravel-redis
        ports:
            - "6379:6379"
        networks:
            - laravel
        volumes:
            - redis_data:/data

networks:
    laravel:

volumes:
    mysql_data:
    redis_data:
